#! /usr/bin/python3

import csv

with open('file1.csv') as f1:
    lf1 = list(csv.reader(f1))
with open('file2.csv') as f2:
    lf2 = list(csv.reader(f2))
for i in lf1:
    for j in lf2:
        if i[0] == j[0] and i[1] != j[1]:
            print(i[0],j[1]+' -->',i[1])
        if i[0] == j[0] and i[2] != j[2]:
            print(i[0],j[2]+' -->',i[2])

