#! /usr/bin/python3

import csv

f1 = csv.reader(open('file1.csv'))
f2 = csv.reader(open('file2.csv'))
lf1 =list(f1)
lf2 =list(f2)
country_changed = []
for i in lf1:
    for j in lf2:
        if i[0] == j[0] and i[1] != j[1]:
            print(i[0],j[1]+' -->',i[1])
        if i[0] == j[0] and i[2] != j[2]:
            print(i[0],j[2]+' -->',i[2])
