#!/usr/bin/python3

import csv 

f = open('/home/joe/sales.csv')
reader = csv.reader(f)
row1 = next(reader) 
print(row1[0], row1[1], row1[5]) 
for i in reader:
    if i[0] == 'Asia':
        print(i[0],i[1],i[5])
f.close()

