#!/usr/bin/python3

import os
import os.path
import glob
from datetime import datetime

today = datetime.today()
print('Below files are delete.')
for i in glob.glob('/home/joe/Temp/*'):
    mtime = datetime.fromtimestamp(os.stat(i)[8])
    filetime = mtime - today
    if filetime.days <= -7:
        print('{:<20} {}'.format(os.path.basename(i),filetime.days))
        os.remove(i)
