#!/usr/bin/python3

# Using Platform model
import platform
print(platform.architecture()[0])

# Without Platform module
def cpuinfo(my_cpu):
    with open('/proc/cpuinfo') as f:
        r = f.read().splitlines()
        cpu = [ i.replace('\t', '') for i in r if i.startswith('flags') or i.startswith('Features')]
        my_cpu(cpu) 

@cpuinfo
def bit(cpu):
    flag = cpu[0].split()
    if 'lm' in flag:
        print('64bit')
    else:
        print('32bit')
