#!/usr/bin/python3
import csv

f = open('/etc/passwd')
r = csv.reader(f, delimiter = ':')
user = []
for row in r:
    user += [row[0]]
if 'runner' in user:
    print('User exists')
else:
    print('User does not exists')
