#!/usr/bin/python3

f = open('/proc/net/dev')
r = f.read().splitlines()
net_data = {}
for data in r[2:]:
    data = data.split(':')
    if data[0].strip() != 'lo':
        net_data[data[0]] = [float(data[1].split()[0])/(1024*1024), 
                             float(data[1].split()[8])/(1024*1024)]
for i in net_data.items():
    print('{}: Downloaded {:1.2f} MiB,  Uploaded:{:1.2f} MiB'.format(i[0],i[1][0],i[1][1]))
